In [1]:
import torch

In [2]:
torch.__version__

'2.5.1+cu121'

In [3]:
# scaler 
scaler = torch.tensor(6)
scaler.item()

6

In [4]:
# creat vector of tensor 
vector = torch.tensor([7,7])
vector , vector.ndim


(tensor([7, 7]), 1)

In [5]:
# identify the shape of the tensor 
vector.shape , scaler.shape

(torch.Size([2]), torch.Size([]))

In [6]:
# matrix 
matrix = torch.tensor([[2,3],[5,6]])
matrix , matrix.ndim

(tensor([[2, 3],
         [5, 6]]),
 2)

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
d3_tensor = torch.tensor([[[1,2],[3,4],[5,6]]])
d3_tensor , d3_tensor.ndim , d3_tensor.shape

(tensor([[[1, 2],
          [3, 4],
          [5, 6]]]),
 3,
 torch.Size([1, 3, 2]))

In [9]:
# creating random tensor 
random_tensor = torch.rand(size=(2,3))
random_tensor , random_tensor.ndim

(tensor([[0.9637, 0.7119, 0.3594],
         [0.3939, 0.2936, 0.5978]]),
 2)

In [10]:
random_tensor.dtype

torch.float32

In [11]:
# zeros and ones 
zeros = torch.zeros(size=(2,2,8))
zeros

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [12]:
ones = torch.ones(size=(2,2,8))
ones


tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [13]:
#arange 
t_tensor = torch.arange(0,10,1)
t_tensor , t_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [15]:
r_tensor = torch.tensor(data=[4,5,6],
                        dtype=torch.float32,
                        device='cpu',
                        requires_grad=False)
r_tensor, r_tensor.dtype, r_tensor.device

(tensor([4., 5., 6.]), torch.float32, device(type='cpu'))

## Tensor Operation 
##### multiplication  division  addition  suptraction


In [16]:
x = torch.tensor([2,3,4])
x

tensor([2, 3, 4])

In [17]:
x = x + 2
x = x - 2
x = x * 2
x = x / 2
x

tensor([2., 3., 4.])

In [18]:
x = torch.multiply(x , 10)
x

tensor([20., 30., 40.])

In [19]:
x = torch.matmul(x, x)
x

tensor(2900.)

In [21]:
# manual seed generation  /// used to make random vales constant 

torch.manual_seed(42)

random_tens = torch.rand((2,3))
random_tens

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [22]:
from torch import nn

In [23]:
linear_layer = nn.Linear(6,4)

random_l = torch.rand(size=(4,6))

x = linear_layer(random_l)
x

tensor([[ 0.6558,  0.0566,  0.1838, -0.5983],
        [ 0.6037,  0.2153, -0.0014, -0.6023],
        [ 0.5914,  0.0809,  0.1573, -0.5555],
        [ 0.8549,  0.0615,  0.2566, -0.5615]], grad_fn=<AddmmBackward0>)

In [25]:
v = torch.arange(0,16,2)
v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [27]:
v.min()

tensor(0)

In [28]:
v.max()

tensor(14)

In [29]:
v.argmax()

tensor(7)

In [30]:
v.argmin()

tensor(0)